name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex cheat-sheet
        uses: dante-ev/latex-action@latest
        with:
          root_file: cheat-sheet.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: cheat-sheet.pdf
          path: cheat-sheet.pdf
      - name: Make directory
        run: mkdir public
      - name: Move file
        run: mv cheat-sheet.pdf public/cheat-sheet.pdf
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          destination_dir: assets
          enable_jekyll: true
